version: "2.4"

services:
    app:
        build:
            context: packages/inventory-app
        image: inventory-app-dev
        volumes:
            - "./packages/inventory-app:/inventory/inventory-app"
            - "app-node-modules:/inventory/inventory-app/node_modules"
        ports:
            - "3000:3000"
        depends_on:
            - api

    api:
        build:
            context: packages/inventory-api
        image: inventory-api-dev
        volumes:
            - "./packages/inventory-api:/inventory/inventory-api"
            - "api-node-modules:/inventory/inventory-api/node_modules"
        environment: 
            API_DB_CONNECTION_STRING: "postgres://inventory-user:inventory-pwd@db:5432/inventory"
        ports:
            - "9000:9000"
            - "9042:9042"
        depends_on:
            - db

    db:
        image: postgres:12.2-alpine
        ports:
            - "5433:5433"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: inventory
            POSTGRES_USER: inventory-user
            POSTGRES_PASSWORD: inventory-pwd
            POSTGRES_HOST: "0.0.0.0:5433"

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - "8080:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: test
            PGADMIN_DEFAULT_PASSWORD: test
        depends_on:
            - db

volumes:
    postgres_data:
    api-node-modules:
    app-node-modules: