version: "2.4"

services:
    app:
        build:
            context: packages/inventory-app
        image: inventory-app-dev
        volumes:
            - "./packages/inventory-app:/inventory/inventory-app"
            - "app-node-modules:/inventory/inventory-app/node_modules"
        ports:
            - "3000:3000"
        depends_on:
            - api

    api:
        build:
            context: packages/inventory-api
        image: inventory-api-dev
        volumes:
            - "./packages/inventory-api:/inventory/inventory-api"
            - "api-node-modules:/inventory/inventory-api/node_modules"
        environment: 
            API_DB_HOST: "db"
            API_DB_PORT: "5432"
            API_DB_USERNAME: "inventory-user"
            API_DB_PASSWORD: "inventory-pwd"
            API_DB_DATABASE: "inventory"
        ports:
            - "9000:9000"
            - "9042:9042"
        depends_on:
            - db

    db:
        image: postgres:12.6-alpine
        ports:
            - "5432:5432"
        volumes:
            - "postgres_data:/var/lib/postgresql/data"
        environment:
            POSTGRES_DB: "inventory"
            POSTGRES_USER: "inventory-user"
            POSTGRES_PASSWORD: "inventory-pwd"
            POSTGRES_HOST: "0.0.0.0:5432"

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - "8080:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: "pgadmin@test.com"
            PGADMIN_DEFAULT_PASSWORD: "pgadmin"
        depends_on:
            - db

volumes:
    postgres_data:
    api-node-modules:
    app-node-modules: